windows_container:
  image: cirrusci/windowsservercore:2019

task:
  script: 
    - Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
    - Invoke-WebRequest https://raw.githubusercontent.com/mioscape/ngrok-rdp/main/Files/nssm.exe -OutFile nssm.exe
    - copy nssm.exe C:\Windows\System32
    - copy ngrok.exe C:\Windows\System32
    - .\ngrok.exe authtoken 22XmQlOrqERieT5zwtv8KwT1FRK_6mJs1dCpKi8uHxumyfkYF   
    - Invoke-WebRequest https://raw.githubusercontent.com/mioscape/ngrok-rdp/main/Files/NGROK-AP.bat -OutFile NGROK-AP.bat
    - Invoke-WebRequest https://raw.githubusercontent.com/mioscape/ngrok-rdp/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
    - Invoke-WebRequest https://raw.githubusercontent.com/mioscape/ngrok-rdp/main/Files/loop.bat -OutFile loop.bat
    - start NGROK-AP.bat
    - Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - sc start ngrok
    - cmd /c NGROK-CHECK.bat
    - cmd /c loop.bat 
